version: '3.9'
services:
  node-api:
    image: ghcr.io/gianni963/cicd-projet2/node-api:latest
    pull_policy: always
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  frontend:
    image: ghcr.io/gianni963/cicd-projet2/frontend:latest
    pull_policy: always
    ports:
      - target: 80
        published: 80
    restart: always