name: CI/CD workflow !
on: push
jobs:
  build-frontend-and-node-api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - context_name: ./frontend
          image_name: ghcr.io/gianni963/cicd-projet2/frontend:latest
        - context: ./node-api
          image-name: ghcr.io/gianni963/cicd-projet2/node-api:latest
    permissions:
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3
      - name: docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image_name }}
      - name: login to github contaner registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context_name }}
          push: true
          tags: ${{ matrix.image_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max]



 