name: CI/CD workflow !
on: push
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: setuo docker buildx
        uses: docker/setup-buildx-actions@v3"
      - name: login to github contaner registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-actions@v5
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/gianni963/cicd-projet2/frontend:latest

      
